waveform_approximant_estimation: "IMRPhenomPv2"
waveform_approximant_injection: "IMRPhenomPv2"
reference_frequency: 10.0
max_reference_frequency: 60.0
reference_frequency_steps: 5.0
minimum_frequency: 10.0
maximum_frequency: 100.0
sampling_frequency: 4096
geocent_time: 1126259642.413
duration: 4
num_events: 2
priors_lower_bound: 0.8 # means lower bound of uniform prior distribution is the respective injection value time priors_lower_bound
priors_upper_bound: 1.2 # means lower bound of uniform prior distribution is the respective injection value time priors_lower_bound
detector_setup: ["H1", "L1"]
npoints: 500
population_file: "population.json"
results_dir: "results"
bias_output_file: "biases.csv"
population_paramters:

# paramters. estimate either true or false dependent on you wish to estimate this parameter. min max is for the population generation
# if you want to fix a parameter in the population generation simply set min max equal (this has not necessarily something to do with the priors)
parameters:
  mass_1:
    estimate: true
    min: 100
    max: 200
  mass_2:
    estimate: true
    min: 50
    max: 150
  a_1:
    estimate: false
    min: 0
    max: 0
  a_2:
    estimate: false
    min: 0
    max: 0
  tilt_1:
    estimate: false
    min: 0
    max: 0
  tilt_2:
    estimate: false
    min: 0
    max: 0
  phi_12:
    estimate: false
    min: 0
    max: 0
  phi_jl:
    estimate: false
    min: 0
    max: 0
  luminosity_distance:
    estimate: false
    min: 1000
    max: 5000
  theta_jn:
    estimate: false
    min: 0
    max: 0
  psi:
    estimate: false
    min: 0
    max: 0
  phase:
    estimate: false
    min: 0
    max: 0
  ra:
    estimate: false
    min: 0
    max: 0 
  dec:
    estimate: false
    min: 0
    max: 0